'use client';

import React, { useState } from 'react';
import { usePlayer } from '@/context/PlayerContext';
import { Track, Playlist } from '@/lib/types';
import { savePlaylist, getLastFmConfig } from '@/lib/storage';
import { Wand2, Sparkles, Play, Plus, Check, RefreshCw, Radio } from 'lucide-react';

export function SmartMixGenerator() {
  const { playTrack, accentColor } = usePlayer();
  const [selectedMood, setSelectedMood] = useState<string>('chill');
  const [selectedGenre, setSelectedGenre] = useState<string>('R&B / Soul');
  const [seedArtist, setSeedArtist] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [generatedMix, setGeneratedMix] = useState<Track[]>([]);
  const [isSaved, setIsSaved] = useState<boolean>(false);

  const moods = [
    { id: 'energetic', label: '⚡ Energetic', query: 'Upbeat pop dance hits' },
    { id: 'chill', label: '☕ Chill & Relax', query: 'Chill indie r&b lofi' },
    { id: 'focus', label: '🧠 Deep Focus', query: 'Ambient study instrumental beats' },
    { id: 'melancholic', label: '🌧️ Melancholic', query: 'Sad acoustic emotional ballad' },
    { id: 'workout', label: '🔥 Workout Beast', query: 'High energy gym workout phonk rock' },
    { id: 'discovery', label: '🧭 Deep Discovery', query: 'Alternative underground fresh tracks' },
  ];

  const genres = [
    'R&B / Soul',
    'Synthwave & Retrowave',
    'Hip-Hop & Rap',
    'Indie Pop & Alternative',
    'Electronic / House',
    'Rock / Post-Punk',
    'Lo-Fi Beats',
  ];

  const handleGenerate = async () => {
    setIsGenerating(true);
    setIsSaved(false);
    try {
      const moodObj = moods.find((m) => m.id === selectedMood);
      let query = `${selectedGenre} ${moodObj?.query || ''}`;
      if (seedArtist.trim()) {
        query = `${seedArtist.trim()} ${selectedGenre} ${moodObj?.id || ''}`;
      }

      const res = await fetch(`/api/search?q=${encodeURIComponent(query)}&filter=songs`);
      if (res.ok) {
        const data = await res.json();
        const songs: Track[] = data.songs || [];
        
        // If seed artist provided, also fetch related radio
        if (songs.length > 0) {
          const radioRes = await fetch(`/api/radio?id=${encodeURIComponent(songs[0].id)}`);
          if (radioRes.ok) {
            const radioData = await radioRes.json();
            const combined = [...songs.slice(0, 8), ...(radioData.tracks || []).slice(0, 12)];
            // Deduplicate by ID
            const unique = Array.from(new Map(combined.map((t) => [t.id, t])).values());
            setGeneratedMix(unique);
          } else {
            setGeneratedMix(songs);
          }
        } else {
          setGeneratedMix(songs);
        }
      }
    } catch (e) {
      console.error('Error generating mix:', e);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSaveToLibrary = async () => {
    if (generatedMix.length === 0) return;
    const newPlaylist: Playlist = {
      id: `smart_mix_${Date.now()}`,
      title: `${selectedGenre} (${selectedMood.toUpperCase()} Mix)`,
      description: `Algorithmic Smart Playlist generated by LastWave Taste Engine`,
      coverUrl: generatedMix[0]?.coverUrl,
      itemCount: generatedMix.length,
      tracks: generatedMix,
      createdAt: Date.now(),
      isSmart: true,
    };
    await savePlaylist(newPlaylist);
    setIsSaved(true);
  };

  const handlePlayAll = () => {
    if (generatedMix.length > 0) {
      playTrack(generatedMix[0], generatedMix, 0);
    }
  };

  return (
    <div className="space-y-6 pb-32">
      {/* Title */}
      <div className="space-y-1">
        <h1 className="text-2xl font-black text-white tracking-tight flex items-center gap-2">
          <Wand2 className="w-6 h-6 text-brand-accent" />
          Smart Playlist Generator
        </h1>
        <p className="text-xs text-zinc-400">
          Synthesize custom algorithmic mixes tailored to your mood, genres, and favorite artists.
        </p>
      </div>

      {/* Mood Selector Chips */}
      <div className="space-y-2">
        <label className="text-xs font-bold uppercase tracking-wider text-zinc-400">
          1. Choose Mood / Energy
        </label>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
          {moods.map((m) => {
            const isSel = selectedMood === m.id;
            return (
              <button
                key={m.id}
                onClick={() => setSelectedMood(m.id)}
                className={`py-2.5 px-3 rounded-2xl text-xs font-semibold text-left transition active:scale-95 border ${
                  isSel
                    ? 'bg-brand-accent text-zinc-950 border-brand-accent shadow-md'
                    : 'bg-zinc-900/60 text-zinc-300 border-white/5 hover:bg-white/10'
                }`}
              >
                {m.label}
              </button>
            );
          })}
        </div>
      </div>

      {/* Genre Selector Chips */}
      <div className="space-y-2">
        <label className="text-xs font-bold uppercase tracking-wider text-zinc-400">
          2. Choose Genre DNA
        </label>
        <div className="flex flex-wrap gap-2">
          {genres.map((g) => {
            const isSel = selectedGenre === g;
            return (
              <button
                key={g}
                onClick={() => setSelectedGenre(g)}
                className={`py-1.5 px-3 rounded-full text-xs font-semibold transition active:scale-95 border ${
                  isSel
                    ? 'bg-white text-zinc-950 border-white'
                    : 'bg-zinc-900/60 text-zinc-400 border-white/5 hover:bg-white/10'
                }`}
              >
                {g}
              </button>
            );
          })}
        </div>
      </div>

      {/* Optional Seed Artist */}
      <div className="space-y-2">
        <label className="text-xs font-bold uppercase tracking-wider text-zinc-400">
          3. Seed Artist (Optional)
        </label>
        <input
          type="text"
          value={seedArtist}
          onChange={(e) => setSeedArtist(e.target.value)}
          placeholder="e.g. Daft Punk, The Weeknd, SZA..."
          className="w-full px-4 py-3 bg-zinc-900/80 border border-white/10 rounded-2xl text-zinc-100 placeholder-zinc-500 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-brand-accent transition"
        />
      </div>

      {/* Generate Mix Button */}
      <button
        onClick={handleGenerate}
        disabled={isGenerating}
        className="w-full py-3.5 rounded-2xl text-sm font-bold text-zinc-950 flex items-center justify-center gap-2 shadow-xl transition active:scale-95"
        style={{
          backgroundColor: accentColor || '#C6F100',
          boxShadow: `0 8px 25px ${accentColor}40`,
        }}
      >
        {isGenerating ? (
          <>
            <RefreshCw className="w-4 h-4 animate-spin" />
            Synthesizing Algorithmic Mix...
          </>
        ) : (
          <>
            <Sparkles className="w-4 h-4" />
            Generate Smart Mix
          </>
        )}
      </button>

      {/* Generated Tracklist */}
      {generatedMix.length > 0 && (
        <div className="space-y-3 pt-2">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-bold text-zinc-200">
              Generated Mix ({generatedMix.length} tracks)
            </h3>
            <div className="flex items-center space-x-2">
              <button
                onClick={handleSaveToLibrary}
                className="px-3 py-1.5 rounded-full bg-zinc-800 text-xs font-semibold text-zinc-200 hover:text-white flex items-center gap-1 transition"
              >
                {isSaved ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Plus className="w-3.5 h-3.5" />}
                {isSaved ? 'Saved' : 'Save'}
              </button>
              <button
                onClick={handlePlayAll}
                className="px-3.5 py-1.5 rounded-full bg-white text-zinc-950 text-xs font-bold flex items-center gap-1 transition active:scale-95 shadow"
              >
                <Play className="w-3.5 h-3.5 fill-current" />
                Play Mix
              </button>
            </div>
          </div>

          <div className="space-y-1.5">
            {generatedMix.map((track, idx) => (
              <div
                key={`${track.id}-${idx}`}
                onClick={() => playTrack(track, generatedMix, idx)}
                className="flex items-center justify-between p-2.5 rounded-2xl bg-zinc-900/40 hover:bg-zinc-900/80 border border-white/5 cursor-pointer transition active:scale-[0.98]"
              >
                <div className="flex items-center space-x-3 truncate">
                  <span className="text-xs font-bold text-zinc-500 w-4 text-center">
                    {idx + 1}
                  </span>
                  <img
                    src={track.coverUrl}
                    alt=""
                    className="w-10 h-10 rounded-xl object-cover bg-zinc-800 flex-shrink-0"
                  />
                  <div className="truncate">
                    <h4 className="text-sm font-semibold text-zinc-200 truncate">{track.title}</h4>
                    <p className="text-xs text-zinc-400 truncate">{track.artist}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
